// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmkzdjfuvrmiiefbdfui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtta3pkamZ1dnJtaWllZmJkZnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMzEyMjYsImV4cCI6MjA4NTYwNzIyNn0.eqlLJAoOjXjS7zglYd2araY6RUaF7OnTlihpOWIVkNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});